name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Get changed files
      id: get_changed_files
      run: |
        # Get the list of changed files in the latest commit
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Output the changed files as a newline-separated string
        echo "::set-output name=changed_files::$changed_files"

    